Repository andela/riders-ah-frontend, pull requests merged in 2019-07, with the labels that each got.

#9 #166869731 Create the landing page
  .travis.yml
  Procfile
  cypress.json
  cypress/integration/home/landing.spec.js
  helpers/utils/testUtils.js
  jest.config.js
  package.json
  server.js
  src/__mocks__/fileMock.js
  src/app.js
  src/assets/scss/_config.scss
  src/assets/scss/_container.scss
  src/assets/scss/_input.scss
  src/assets/scss/_landing-page.scss
  src/assets/scss/_navbar.scss
  src/assets/scss/main.scss
  src/assets/videos/bg-video.mp4
  src/components/index.js
  src/components/routes.jsx
  src/reducers/index.js
  src/store.js
  src/tests/views/home.test.js
  src/views/home.jsx
  src/views/index.js
  src/views/routes.js
  webpack/base.config.js
  webpack/dev.config.js
Labels: TTL REVIEW

#13 #165413063 signup and register a user
  cypress/integration/examples/signup.spec.js
  package.json
  src/actions/index.js
  src/actions/signup.js
  src/actions/types.js
  src/actions/verification.js
  src/app.js
  src/assets/scss/_container.scss
  src/assets/scss/_input.scss
  src/components/authentication/signup.jsx
  src/components/authentication/verification.jsx
  src/components/common/button.jsx
  src/components/common/input.jsx
  src/helpers/helpers.js
  src/helpers/httpServices.js
  src/reducers/index.js
  src/reducers/signup.js
  src/reducers/testReducer.js
  src/reducers/verify.js
  src/store.js
  src/tests/components/authentication/signup.test.js
  src/tests/reducers/signup.test.js
  src/utils/errorHandler.js
  src/views/routes.js
  webpack/base.config.js
Labels: TTL REVIEW

#10 #165413064 add password reset functionality
  .travis.yml
  cypress.json
  cypress/integration/reset.spec.js
  helpers/utils/testUtils.js
  package.json
  src/actions/resetPassword.js
  src/actions/types.js
  src/app.js
  src/assets/scss/_input.scss
  src/components/authentication/CompleteResetPassword.jsx
  src/components/authentication/ResetPassword.jsx
  src/components/common/button.jsx
  src/components/common/input.jsx
  src/components/common/resetForm.jsx
  src/components/index.js
  src/components/routes.jsx
  src/helpers/helpers.js
  src/helpers/httpServices.js
  src/index.html
  src/index.js
  src/reducers/index.js
  src/reducers/resetPasswordReducer.js
  src/setupTests.js
  src/store.js
  src/tests/actions/resetPassword.test.js
  src/tests/app.test.js
  src/tests/components/resetPassword.test.js
  src/tests/reducers/resetPassword.test.js
  src/utils/actionUtil.js
  src/utils/errorHandler.js
  src/views/home.jsx
  src/views/routes.js
  webpack/base.config.js
  webpack/dev.config.js
  webpack/prod.config.js
Labels: TTL REVIEW

#12 #165413065 Add the user login functionality
  .eslintrc
  cypress/integration/examples/login.spec.js
  helpers/credentialsValidation.js
  helpers/httpServices.js
  helpers/privateRoute.js
  package.json
  src/actions/login.js
  src/actions/types.js
  src/app.js
  src/assets/scss/_errorMessage.scss
  src/assets/scss/_input.scss
  src/assets/scss/_link.scss
  src/assets/scss/_navbar.scss
  src/assets/scss/main.scss
  src/components/articles/viewArticles.jsx
  src/components/authentication/localLogin.jsx
  src/components/authentication/login.jsx
  src/components/authentication/signup.jsx
  src/components/common/button.jsx
  src/components/common/errorMessage.jsx
  src/components/common/input.jsx
  src/reducers/index.js
  src/reducers/loginReducer.js
  src/store.js
  src/tests/actions/loginActions.test.js
  src/tests/components/articles/viewArticles.test.js
  src/tests/components/authentication/localLogin.test.js
  src/tests/components/authentication/login.test.js
  src/tests/components/authentication/signup.test.js
  src/tests/reducers/loginReducer.test.js
  src/tests/reducers/signup.test.js
  src/views/routes.js
  webpack/base.config.js
  webpack/dev.config.js
Labels: TTL REVIEW

#11 #165413066 Add social login feature
  package.json
  src/actions/socialLogin.js
  src/actions/types.js
  src/assets/images/facebook.png
  src/assets/images/gmail.png
  src/assets/images/twitter.png
  src/assets/scss/_login.scss
  src/components/authentication/login.jsx
  src/components/index.jsx
  src/store/actions/index.js
  src/store/actions/types.js
  src/tests/actions/login.test.js
  src/tests/components/articles/articles.test.js
  src/tests/components/authentication/login.test.js
  src/tests/store/actions/types.js
  src/tests/views/notFound.js
  src/tests/views/routes.test.js
  src/views/notFound.jsx
  src/views/routes.js
  webpack/dev.config.js
Labels: TTL REVIEW

#21 #167311752 Set Heroku environment for pipeline
  app.json
Labels: TTL REVIEW, peer review

#15 #165413068 add functionalities for creating and updating an article
  package.json
  src/actions/articleAction.js
  src/actions/types.js
  src/app.js
  src/assets/images/avatar.png
  src/assets/images/profile_avatar.png
  src/assets/images/writing.png
  src/assets/scss/_config.scss
  src/assets/scss/_createArticle.scss
  src/assets/scss/_input.scss
  src/assets/scss/_navbar.scss
  src/assets/scss/main.scss
  src/components/articles/createOrUpdateArticle.jsx
  src/components/articles/editor.jsx
  src/components/authentication/localLogin.jsx
  src/components/common/button.jsx
  src/components/common/navBar.jsx
  src/components/common/resetForm.jsx
  src/components/index.js
  src/helpers/helpers.js
  src/reducers/articleReducer.js
  src/reducers/index.js
  src/setupTests.js
  src/tests/actions/createOrUpdateArticle.test.js
  src/tests/components/articles/article.test.js
  src/tests/components/articles/createOrUpdateArticle.test.js
  src/tests/components/authentication/resetPassword.test.js
  src/tests/reducers/createArticle.test.js
  src/utils/errorHandler.js
  src/views/routes.js
Labels: TTL REVIEW

#20 Ft view articles 167064436
  package.json
  src/actions/oneStory.js
  src/actions/types.js
  src/actions/viewArticles.js
  src/assets/images/animation.gif
  src/assets/images/delete.png
  src/assets/images/pexels-photo-46710.jpeg
  src/assets/images/update.png
  src/assets/scss/_articleCard.scss
  src/assets/scss/_config.scss
  src/assets/scss/_container.scss
  src/assets/scss/_loader.scss
  src/assets/scss/_navbar.scss
  src/assets/scss/_oneStory.scss
  src/assets/scss/main.scss
  src/components/articles/articleCard.jsx
  src/components/articles/oneStory.jsx
  src/components/articles/viewArticles.jsx
  src/components/authentication/login.jsx
  src/components/common/loader.jsx
  src/components/menu/author.jsx
  src/components/menu/navBar.jsx
  src/components/routes.jsx
  src/reducers/index.js
  src/reducers/oneStory.js
  src/reducers/viewArticles.js
  src/tests/components/articles/article.test.js
  src/tests/components/articles/viewArticles.test.js
  src/tests/components/authentication/login.test.js
  src/tests/components/common/loader.test.js
  src/tests/components/menu/author.test.js
  src/views/home.jsx
  src/views/routes.js
Labels: TTL REVIEW

#19 #165413070 user should comment on articles
  cypress/integration/examples/login.spec.js
  helpers/commentToggle.js
  package.json
  src/actions/comment.js
  src/actions/types.js
  src/app.js
  src/assets/images/thumbs-up-hand-symbol.png
  src/assets/scss/_comment.scss
  src/assets/scss/_config.scss
  src/assets/scss/_errorMessage.scss
  src/assets/scss/_menu.scss
  src/assets/scss/main.scss
  src/components/articles/articleCard.jsx
  src/components/articles/oneStory.jsx
  src/components/articles/viewArticles.jsx
  src/components/comment/readComment.jsx
  src/components/comment/writeComment.jsx
  src/components/common/errorMessage.jsx
  src/components/common/userProfile.jsx
  src/components/menu/author.jsx
  src/reducers/commentReducer.js
  src/reducers/index.js
  src/reducers/viewArticlesReducer.js
  src/tests/actions/commentActions.test.js
  src/tests/app.test.js
  src/tests/components/articles/article.test.js
  src/tests/components/articles/oneStory.test.js
  src/tests/components/comment/readComment.test.js
  src/tests/components/comment/writeComment.test.js
  src/tests/reducers/commentReducer.test.js
  src/utils/errorHandler.js
  src/views/routes.js
  webpack/dev.config.js
Labels: TTL REVIEW

#16 #165413067 View and edit profile
  package.json
  src/actions/profile/getUserInfo.js
  src/actions/profile/index.js
  src/actions/profile/updateUser.js
  src/actions/types.js
  src/assets/images/default.png
  src/assets/scss/_card.scss
  src/assets/scss/_input.scss
  src/assets/scss/_landing-page.scss
  src/assets/scss/_navbar.scss
  src/assets/scss/_user-profile.scss
  src/assets/scss/main.scss
  src/assets/scss/modal.scss
  src/components/articles/oneStory.jsx
  src/components/common/button.jsx
  src/components/common/index.js
  src/components/common/modal.js
  src/components/common/profileSideMenu.jsx
  src/components/common/userProfile.jsx
  src/components/index.js
  src/components/profile/viewProfile.jsx
  src/helpers/helpers.js
  src/index.html
  src/reducers/index.js
  src/reducers/userReducer.js
  src/setupTests.js
  src/tests/actions/userProfile.test.js
  src/tests/components/articles/article.test.js
  src/tests/components/articles/createOrUpdateArticle.test.js
  src/tests/components/commonComponents.test.js
  src/tests/components/profileCompontents.test.js
  src/tests/helpers/helper.test.js
  src/tests/reducers/profileReducer.test.js
  src/tests/views/routes.test.js
  src/views/home.jsx
  src/views/notFound.jsx
  src/views/routes.js
  webpack/base.config.js
Labels: TTL REVIEW

#17 #165413072 Adds like and dislike functionality
  src/actions/articleAction.js
  src/actions/articles.js
  src/actions/types.js
  src/assets/images/dislike.png
  src/assets/images/like.png
  src/assets/scss/_comment.scss
  src/assets/scss/_oneStory.scss
  src/assets/scss/main.scss
  src/components/articles/createOrUpdateArticle.jsx
  src/components/articles/likeAndDislike.jsx
  src/components/articles/oneStory.jsx
  src/components/menu/author.jsx
  src/helpers/helpers.js
  src/reducers/articleReactReducer.js
  src/reducers/articleReducer.js
  src/reducers/index.js
  src/tests/actions/createOrUpdateArticle.test.js
  src/tests/actions/likeArticle.js
  src/tests/actions/resetPassword.test.js
  src/tests/components/articles/article.test.js
  src/tests/components/articles/oneStory.test.js
  src/tests/reducers/likeArticle.js
Labels: TTL REVIEW

#18 #165413071 articles pagination
  .gitignore
  cypress/integration/.DS_Store
  src/assets/scss/_pagination.scss
  src/assets/scss/main.scss
  src/components/articles/viewArticles.jsx
  src/components/common/pagination.jsx
  src/tests/components/common/pagination.test.js
  src/tests/paginate.test.js
  src/utils/paginate.js
  src/views/routes.js
Labels: TTL REVIEW

#22 #167328280 improve the login feature
  helpers/privateRoute.js
  src/app.js
  src/components/authentication/login.jsx
  src/tests/components/authentication/login.test.js
  src/views/routes.js
Labels: TTL REVIEW

#24 #165413069 Rating an article
  package.json
  src/actions/article/ratingAction.js
  src/actions/types.js
  src/assets/images/Bstar.png
  src/assets/images/Gstar.png
  src/assets/images/star-grey.png
  src/assets/images/star-yellow.png
  src/assets/scss/_navbar.scss
  src/assets/scss/_oneStory.scss
  src/components/articles/oneStory.jsx
  src/components/common/index.js
  src/components/common/rating.js
  src/components/menu/author.jsx
  src/reducers/article/ratingReducer.js
  src/reducers/index.js
  src/tests/components/articles/article.test.js
  src/tests/components/articles/oneStory.test.js
  src/tests/components/articles/rateOneStory.test.js
  src/tests/components/common/rating.test.js
  src/tests/reducers/ratingReducer.test.js
Labels: TTL REVIEW

#25 #167428698 social signup
  src/components/authentication/login.jsx
  src/components/authentication/signup.jsx
  src/components/authentication/socialAuth.jsx
  src/tests/components/authentication/login.test.js
  src/tests/components/authentication/social.test.js
Labels: TTL REVIEW

#26 #167317540 change signup implementation
  src/actions/verification.js
  src/components/authentication/signup.jsx
  src/helpers/helpers.js
  src/reducers/signup.js
  src/tests/actions/accountVerification.test.js
  src/tests/reducers/signup.test.js
  src/utils/errorHandler.js
Labels: TTL REVIEW

#32 #167482222 Change create article interface and add description field
  src/actions/articleAction.js
  src/assets/images/upload-icon.png
  src/assets/scss/_createArticle.scss
  src/assets/scss/_oneStory.scss
  src/components/articles/articleCard.jsx
  src/components/articles/createOrUpdateArticle.jsx
  src/components/articles/oneStory.jsx
  src/components/menu/author.jsx
  src/reducers/articleReducer.js
  src/utils/errorHandler.js
Labels: TTL REVIEW

#28 #165413074 share article on social media
  package.json
  src/__mocks__/window.js
  src/assets/scss/_oneStory.scss
  src/components/articles/oneStory.jsx
  src/components/common/shareArticles.jsx
  src/tests/components/common/share.test.js
Labels: peer review

#36 #165413081 list bookmarked articles
  src/actions/bookmarkAction.js
  src/actions/types.js
  src/assets/images/bookmark.png
  src/assets/images/bookmarkClicked.png
  src/assets/scss/_user-profile.scss
  src/components/articles/bookmark.jsx
  src/components/articles/oneStory.jsx
  src/components/profile/viewProfile.jsx
  src/helpers/bookmarkHelper.js
  src/reducers/bookmarkReducer.js
  src/reducers/index.js
  src/tests/components/articles/oneStory.test.js
  src/tests/components/profileCompontents.test.js
  src/tests/reducers/bookmarkReducer.test.js
Labels: TTL REVIEW
